### ISSUE TITLE
Legend (lables) in graphical display

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#26]

**Comment by csasm** [comment]
Suggestions

Circles would be drawn with following colours and text would be written in front of them. Following is description.

Green node :  Responded Node
Yellow node : Queried Node
Blue node :  Contact Node
Black ring : Bootstrap Node
Red Node : Timeout Node
Black Node : No Contact Node

Please send me your suggestion so that i can finaiize it and make a picture and insert to the design

**Comment by rauljim** [comment]
In my opinion, it's important to show nodes that return peers (values). What about this:

Green node : Node responded to query
Yellow node : Queried Node
Blue node : Discovered node (not queried yet)
Black ring : Bootstrap Node (from internal routing table)
Red Node : Timeout Node (failed to respond within 2 seconds)
Dark green node: node returned peers
Black dot in the middle of the node: No Contact Node

I suggest "black dot in the middle of the node" (or something similar) because it can be combined with green (response without peers) and dark green (response with nodes).

**Comment by csasm** [comment]
The legends have been named as per discussion, please let me know if there is need for change

**Comment by rauljim** [comment]
I'm missing "response with peers".
The text in the legend looks pixelated, can you use "real text" instead?

**Comment by csasm** [comment]
I have incorporated both of them. I had no better idea than this presentation of presenting with small circle for peers. If i had given them new colour then it was disturbing existing colour codes.

**Comment by rauljim** [comment]
I'm not completely convinced (still think that different colors would be better) but maybe you are right. Leave like this for now.
